# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/daisyplus_openssd_micron_4c2w_66.6mhz_from_50mhz_refined/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_2/sys_top_v2nfc_0_2.xci
# IP: The module: 'sys_top_v2nfc_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/daisyplus_openssd_micron_4c2w_66.6mhz_from_50mhz_refined/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_2/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] -quiet

# XDC: c:/daisyplus_openssd_micron_4c2w_66.6mhz_from_50mhz_refined/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_2/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/daisyplus_openssd_micron_4c2w_66.6mhz_from_50mhz_refined/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_2/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: C:/daisyplus_openssd_micron_4c2w_66.6mhz_from_50mhz_refined/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_2/sys_top_v2nfc_0_2.xci
# IP: The module: 'sys_top_v2nfc_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/daisyplus_openssd_micron_4c2w_66.6mhz_from_50mhz_refined/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_2/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] -quiet

# XDC: c:/daisyplus_openssd_micron_4c2w_66.6mhz_from_50mhz_refined/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_2/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/daisyplus_openssd_micron_4c2w_66.6mhz_from_50mhz_refined/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_2/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
