# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/daisyplus_openssd_micron_4c2w_80mhz_from_50mhz_real/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_auto_cc_4/sys_top_auto_cc_4.xci
# IP: The module: 'sys_top_auto_cc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/daisyplus_openssd_micron_4c2w_80mhz_from_50mhz_real/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_auto_cc_4/sys_top_auto_cc_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_auto_cc_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/daisyplus_openssd_micron_4c2w_80mhz_from_50mhz_real/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_auto_cc_4/sys_top_auto_cc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_auto_cc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/daisyplus_openssd_micron_4c2w_80mhz_from_50mhz_real/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_auto_cc_4/sys_top_auto_cc_4.xci
# IP: The module: 'sys_top_auto_cc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/daisyplus_openssd_micron_4c2w_80mhz_from_50mhz_real/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_auto_cc_4/sys_top_auto_cc_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_auto_cc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/daisyplus_openssd_micron_4c2w_80mhz_from_50mhz_real/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_auto_cc_4/sys_top_auto_cc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_auto_cc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
