# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/daisyplus_openssd_micron_4c2w_50mhz/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0.xci
# IP: The module: 'sys_top_pll_bank13_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/daisyplus_openssd_micron_4c2w_50mhz/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_pll_bank13_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/daisyplus_openssd_micron_4c2w_50mhz/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_pll_bank13_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/daisyplus_openssd_micron_4c2w_50mhz/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_pll_bank13_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/daisyplus_openssd_micron_4c2w_50mhz/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0.xci
# IP: The module: 'sys_top_pll_bank13_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/daisyplus_openssd_micron_4c2w_50mhz/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_pll_bank13_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/daisyplus_openssd_micron_4c2w_50mhz/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_pll_bank13_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/daisyplus_openssd_micron_4c2w_50mhz/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_pll_bank13_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
