# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/sys_top_nvme_ctrl_0_0.xci
# IP: The module: 'sys_top_nvme_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/pcie4_uscale_plus_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0 || ORIG_REF_NAME==pcie4_uscale_plus_0} -quiet] -quiet

# IP: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/ip_0/pcie4_uscale_plus_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0_gt || ORIG_REF_NAME==pcie4_uscale_plus_0_gt} -quiet] -quiet

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt_ooc.xdc

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0_gt || ORIG_REF_NAME==pcie4_uscale_plus_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_ooc.xdc

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_late.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0 || ORIG_REF_NAME==pcie4_uscale_plus_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_x1y0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0 || ORIG_REF_NAME==pcie4_uscale_plus_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# IP: D:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/sys_top_nvme_ctrl_0_0.xci
# IP: The module: 'sys_top_nvme_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/pcie4_uscale_plus_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0 || ORIG_REF_NAME==pcie4_uscale_plus_0} -quiet] -quiet

# IP: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/ip_0/pcie4_uscale_plus_0_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0_gt || ORIG_REF_NAME==pcie4_uscale_plus_0_gt} -quiet] -quiet

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt_ooc.xdc

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0_gt || ORIG_REF_NAME==pcie4_uscale_plus_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_ooc.xdc

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0 || ORIG_REF_NAME==pcie4_uscale_plus_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_x1y0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0 || ORIG_REF_NAME==pcie4_uscale_plus_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
