# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_2_0/sys_top_v2nfc_2_0.xci
# IP: The module: 'sys_top_v2nfc_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_2_0/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] -quiet

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_2_0/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_2_0/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: D:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_2_0/sys_top_v2nfc_2_0.xci
# IP: The module: 'sys_top_v2nfc_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_2_0/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] -quiet

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_2_0/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_v2nfc_2_0/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IN_FIFO_ALT_16x512 || ORIG_REF_NAME==IN_FIFO_ALT_16x512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
