# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_blk_mem_gen_2_0_1/sys_top_blk_mem_gen_2_0.xci
# IP: The module: 'sys_top_blk_mem_gen_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_blk_mem_gen_2_0_1/sys_top_blk_mem_gen_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_blk_mem_gen_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_blk_mem_gen_2_0_1/sys_top_blk_mem_gen_2_0.xci
# IP: The module: 'sys_top_blk_mem_gen_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sources/DaisyPlus/NAND/Micron/OpenSSD/512bit/daisyplus_openssd_micron_4c2w/cosm-plus-sys/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_blk_mem_gen_2_0_1/sys_top_blk_mem_gen_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_blk_mem_gen_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
